branch-defaults:
  master:
    environment: rails-test-dev
    group_suffix: null
environment-defaults:
  rails-test-dev:
    branch: null
    repository: null
global:
  application_name: rails_test
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Ruby 2.6 (Puma)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
