branch-defaults:
  default:
    environment: rails-test-dev
environment-defaults:
  rails-test-dev:
    branch: null
    repository: null
global:
  application_name: rails_test
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Passenger with Ruby
    2.6 running on 64bit Amazon Linux/2.11.1
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
